# Generated by Django 5.0.6 on 2024-06-29 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=100)),
                ('candidateName1', models.CharField(max_length=100)),
                ('candidateName2', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('endtime', models.DateTimeField()),
                ('VotesCandidate1', models.ManyToManyField(related_name='VotesCandidate1', to=settings.AUTH_USER_MODEL)),
                ('VotesCandidate2', models.ManyToManyField(related_name='VotesCandidate2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
